<?php
/**
 * DO NOT EDIT! This file is generated by the colors.js script in the scripts folder.
 * To regenerate this file, run 'yarn colors' in the terminal.
 * 
 * 
 * Colors array
 * 
 * @package Lightning_Builder
 * @since 1.0.0
 * 
 * @return array
*/

$bg_colors = [];
$text_colors = [];

if (is_admin()) {

$bg_colors = ['bg-[transparent]' => __('transparent', 'lightning') , 'bg-[#ffffff]' => __('white', 'lightning') , 'bg-[#000C24]' => __('black', 'lightning')];
$text_colors = ['text-[#ffffff]' => __('white', 'lightning') , 'text-[#000000]' => __('black', 'lightning')];

    add_action('admin_head', function () use ($bg_colors, $text_colors) {
        $colors_css = '';

        // merge colors
        $colors = array_merge($bg_colors, $text_colors);

        if (!empty($colors)) {
            foreach ($colors as $key => $value) {
                preg_match_all('/\[(.*?)\]/', $key, $matches);
                $key = $matches[1][0] ?? '';
                $value = strtolower($value);
                $value = str_replace(' ', '-', $value);
                $value = preg_replace('/[^A-Za-z0-9\-]/', '', $value);
                $colors_css .= "body .colors-group .{$value} { background-color: {$key}; }";
            }
        }

        $output_css = '<style class="color-styles">';
        if (!empty($colors_css)) {
            $output_css .= $colors_css;
        }
        $output_css .= '</style>';
        echo $output_css;
    });
}


    