<?php 
// Array of all country codes

$country_codes = [
    "AF" => __("AFGHANISTAN", "lightning"),
    "AL" => __("ALBANIA", "lightning"),
    "DZ" => __("ALGERIA", "lightning"),
    "AS" => __("AMERICAN SAMOA", "lightning"),
    "AD" => __("ANDORRA", "lightning"),
    "AO" => __("ANGOLA", "lightning"),
    "AQ" => __("ANTARCTICA", "lightning"),
    "AG" => __("ANTIGUA AND BARBUDA", "lightning"),
    "AR" => __("ARGENTINA", "lightning"),
    "AM" => __("ARMENIA", "lightning"),
    "AW" => __("ARUBA", "lightning"),
    "AU" => __("AUSTRALIA", "lightning"),
    "AT" => __("AUSTRIA", "lightning"),
    "AZ" => __("AZERBAIJAN", "lightning"),
    "BS" => __("BAHAMAS", "lightning"),
    "BH" => __("BAHRAIN", "lightning"),
    "BD" => __("BANGLADESH", "lightning"),
    "BB" => __("BARBADOS", "lightning"),
    "BY" => __("BELARUS", "lightning"),
    "BE" => __("BELGIUM", "lightning"),
    "BZ" => __("BELIZE", "lightning"),
    "BJ" => __("BENIN", "lightning"),
    "BM" => __("BERMUDA", "lightning"),
    "BT" => __("BHUTAN", "lightning"),
    "BO" => __("BOLIVIA", "lightning"),
    "BA" => __("BOSNIA AND HERZEGOVINA", "lightning"),
    "BW" => __("BOTSWANA", "lightning"),
    "BV" => __("BOUVET ISLAND", "lightning"),
    "BR" => __("BRAZIL", "lightning"),
    "IO" => __("BRITISH INDIAN OCEAN TERRITORY", "lightning"),
    "BN" => __("BRUNEI DARUSSALAM", "lightning"),
    "BG" => __("BULGARIA", "lightning"),
    "BF" => __("BURKINA FASO", "lightning"),
    "BI" => __("BURUNDI", "lightning"),
    "KH" => __("CAMBODIA", "lightning"),
    "CM" => __("CAMEROON", "lightning"),
    "CA" => __("CANADA", "lightning"),
    "CV" => __("CAPE VERDE", "lightning"),
    "KY" => __("CAYMAN ISLANDS", "lightning"),
    "CF" => __("CENTRAL AFRICAN REPUBLIC", "lightning"),
    "TD" => __("CHAD", "lightning"),
    "CL" => __("CHILE", "lightning"),
    "CN" => __("CHINA", "lightning"),
    "CX" => __("CHRISTMAS ISLAND", "lightning"),
    "CC" => __("COCOS (KEELING) ISLANDS", "lightning"),
    "CO" => __("COLOMBIA", "lightning"),
    "KM" => __("COMOROS", "lightning"),
    "CG" => __("CONGO", "lightning"),
    "CD" => __("CONGO, THE DEMOCRATIC REPUBLIC OF THE", "lightning"),
    "CK" => __("COOK ISLANDS", "lightning"),
    "CR" => __("COSTA RICA", "lightning"),
    "CI" => __("CÔTE D'IVOIRE", "lightning"),
    "HR" => __("CROATIA", "lightning"),
    "CU" => __("CUBA", "lightning"),
    "CY" => __("CYPRUS", "lightning"),
    "CZ" => __("CZECH REPUBLIC", "lightning"),
    "DK" => __("DENMARK", "lightning"),
    "DJ" => __("DJIBOUTI", "lightning"),
    "DM" => __("DOMINICA", "lightning"),
    "DO" => __("DOMINICAN REPUBLIC", "lightning"),
    "EC" => __("ECUADOR", "lightning"),
    "EG" => __("EGYPT", "lightning"),
    "SV" => __("EL SALVADOR", "lightning"),
    "GQ" => __("EQUATORIAL GUINEA", "lightning"),
    "ER" => __("ERITREA", "lightning"),
    "EE" => __("ESTONIA", "lightning"),
    "ET" => __("ETHIOPIA", "lightning"),
    "FK" => __("FALKLAND ISLANDS (MALVINAS)", "lightning"),
    "FO" => __("FAROE ISLANDS", "lightning"),
    "FJ" => __("FIJI", "lightning"),
    "FI" => __("FINLAND", "lightning"),
    "FR" => __("FRANCE", "lightning"),
    "GF" => __("FRENCH GUIANA", "lightning"),
    "PF" => __("FRENCH POLYNESIA", "lightning"),
    "TF" => __("FRENCH SOUTHERN TERRITORIES", "lightning"),
    "GA" => __("GABON", "lightning"),
    "GM" => __("GAMBIA", "lightning"),
    "GE" => __("GEORGIA", "lightning"),
    "DE" => __("GERMANY", "lightning"),
    "GH" => __("GHANA", "lightning"),
    "GI" => __("GIBRALTAR", "lightning"),
    "GR" => __("GREECE", "lightning"),
    "GL" => __("GREENLAND", "lightning"),
    "GD" => __("GRENADA", "lightning"),
    "GP" => __("GUADELOUPE", "lightning"),
    "GU" => __("GUAM", "lightning"),
    "GT" => __("GUATEMALA", "lightning"),
    "GN" => __("GUINEA", "lightning"),
    "GW" => __("GUINEA-BISSAU", "lightning"),
    "GY" => __("GUYANA", "lightning"),
    "HT" => __("HAITI", "lightning"),
    "HM" => __("HEARD ISLAND AND MCDONALD ISLANDS", "lightning"),
    "HN" => __("HONDURAS", "lightning"),
    "HK" => __("HONG KONG", "lightning"),
    "HU" => __("HUNGARY", "lightning"),
    "IS" => __("ICELAND", "lightning"),
    "IN" => __("INDIA", "lightning"),
    "ID" => __("INDONESIA", "lightning"),
    "IR" => __("IRAN, ISLAMIC REPUBLIC OF", "lightning"),
    "IQ" => __("IRAQ", "lightning"),
    "IE" => __("IRELAND", "lightning"),
    "IL" => __("ISRAEL", "lightning"),
    "IT" => __("ITALY", "lightning"),
    "JM" => __("JAMAICA", "lightning"),
    "JP" => __("JAPAN", "lightning"),
    "JO" => __("JORDAN", "lightning"),
    "KZ" => __("KAZAKHSTAN", "lightning"),
    "KE" => __("KENYA", "lightning"),
    "KI" => __("KIRIBATI", "lightning"),
    "KP" => __("KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF", "lightning"),
    "KR" => __("KOREA, REPUBLIC OF", "lightning"),
    "KW" => __("KUWAIT", "lightning"),
    "KG" => __("KYRGYZSTAN", "lightning"),
    "LA" => __("LAO PEOPLE'S DEMOCRATIC REPUBLIC (LAOS)", "lightning"),
    "LV" => __("LATVIA", "lightning"),
    "LB" => __("LEBANON", "lightning"),
    "LS" => __("LESOTHO", "lightning"),
    "LR" => __("LIBERIA", "lightning"),
    "LY" => __("LIBYA, STATE OF", "lightning"),
    "LI" => __("LIECHTENSTEIN", "lightning"),
    "LT" => __("LITHUANIA", "lightning"),
    "LU" => __("LUXEMBOURG", "lightning"),
    "MO" => __("MACAO", "lightning"),
    "MK" => __("MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF", "lightning"),
    "MG" => __("MADAGASCAR", "lightning"),
    "MW" => __("MALAWI", "lightning"),
    "MY" => __("MALAYSIA", "lightning"),
    "MV" => __("MALDIVES", "lightning"),
    "ML" => __("MALI", "lightning"),
    "MT" => __("MALTA", "lightning"),
    "MH" => __("MARSHALL ISLANDS", "lightning"),
    "MQ" => __("MARTINIQUE", "lightning"),
    "MR" => __("MAURITANIA", "lightning"),
    "MU" => __("MAURITIUS", "lightning"),
    "YT" => __("MAYOTTE", "lightning"),
    "MX" => __("MEXICO", "lightning"),
    "FM" => __("MICRONESIA, FEDERATED STATES OF", "lightning"),
    "MD" => __("MOLDOVA, REPUBLIC OF", "lightning"),
    "MC" => __("MONACO", "lightning"),
    "MN" => __("MONGOLIA", "lightning"),
    "ME" => __("MONTENEGRO", "lightning"),
    "MS" => __("MONTSERRAT", "lightning"),
    "MA" => __("MOROCCO", "lightning"),
    "MZ" => __("MOZAMBIQUE", "lightning"),
    "MM" => __("MYANMAR", "lightning"),
    "NA" => __("NAMIBIA", "lightning"),
    "NR" => __("NAURU", "lightning"),
    "NP" => __("NEPAL, FEDERAL DEMOCRATIC REPUBLIC OF", "lightning"),
    "NL" => __("NETHERLANDS", "lightning"),
    "AN" => __("NETHERLANDS ANTILLES", "lightning"),
    "NC" => __("NEW CALEDONIA", "lightning"),
    "NZ" => __("NEW ZEALAND", "lightning"),
    "NI" => __("NICARAGUA", "lightning"),
    "NE" => __("NIGER", "lightning"),
    "NG" => __("NIGERIA", "lightning"),
    "NU" => __("NIUE", "lightning"),
    "NF" => __("NORFOLK ISLAND", "lightning"),
    "MP" => __("NORTHERN MARIANA ISLANDS", "lightning"),
    "NO" => __("NORWAY", "lightning"),
    "OM" => __("OMAN", "lightning"),
    "PK" => __("PAKISTAN", "lightning"),
    "PW" => __("PALAU", "lightning"),
    "PS" => __("PALESTINE, STATE OF", "lightning"),
    "PA" => __("PANAMA", "lightning"),
    "PG" => __("PAPUA NEW GUINEA", "lightning"),
    "PY" => __("PARAGUAY", "lightning"),
    "PE" => __("PERU", "lightning"),
    "PH" => __("PHILIPPINES", "lightning"),
    "PN" => __("PITCAIRN", "lightning"),
    "PL" => __("POLAND", "lightning"),
    "PT" => __("PORTUGAL", "lightning"),
    "PR" => __("PUERTO RICO", "lightning"),
    "QA" => __("QATAR", "lightning"),
    "RE" => __("RÉUNION", "lightning"),
    "RO" => __("ROMANIA", "lightning"),
    "RU" => __("RUSSIAN FEDERATION", "lightning"),
    "RW" => __("RWANDA", "lightning"),
    "SH" => __("SAINT HELENA", "lightning"),
    "KN" => __("SAINT KITTS AND NEVIS", "lightning"),
    "LC" => __("SAINT LUCIA", "lightning"),
    "PM" => __("SAINT PIERRE AND MIQUELON", "lightning"),
    "VC" => __("SAINT VINCENT AND THE GRENADINES", "lightning"),
    "WS" => __("SAMOA", "lightning"),
    "SM" => __("SAN MARINO", "lightning"),
    "ST" => __("SAO TOME AND PRINCIPE", "lightning"),
    "SA" => __("SAUDI ARABIA", "lightning"),
    "SN" => __("SENEGAL", "lightning"),
    "RS" => __("SERBIA", "lightning"),
    "SC" => __("SEYCHELLES", "lightning"),
    "SL" => __("SIERRA LEONE", "lightning"),
    "SG" => __("SINGAPORE", "lightning"),
    "SK" => __("SLOVAKIA", "lightning"),
    "SI" => __("SLOVENIA", "lightning"),
    "SB" => __("SOLOMON ISLANDS", "lightning"),
    "SO" => __("SOMALIA", "lightning"),
    "ZA" => __("SOUTH AFRICA", "lightning"),
    "GS" => __("SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS", "lightning"),
    "SS" => __("SOUTH SUDAN", "lightning"),
    "ES" => __("SPAIN", "lightning"),
    "LK" => __("SRI LANKA", "lightning"),
    "SD" => __("SUDAN", "lightning"),
    "SR" => __("SURINAME", "lightning"),
    "SJ" => __("SVALBARD AND JAN MAYEN", "lightning"),
    "SZ" => __("SWAZILAND", "lightning"),
    "SE" => __("SWEDEN", "lightning"),
    "CH" => __("SWITZERLAND", "lightning"),
    "SY" => __("SYRIAN ARAB REPUBLIC", "lightning"),
    "TW" => __("TAIWAN", "lightning"),
    "TJ" => __("TAJIKISTAN", "lightning"),
    "TZ" => __("TANZANIA, UNITED REPUBLIC OF", "lightning"),
    "TH" => __("THAILAND", "lightning"),
    "TL" => __("TIMOR-LESTE", "lightning"),
    "TG" => __("TOGO", "lightning"),
    "TK" => __("TOKELAU", "lightning"),
    "TO" => __("TONGA", "lightning"),
    "TT" => __("TRINIDAD AND TOBAGO", "lightning"),
    "TN" => __("TUNISIA", "lightning"),
    "TR" => __("TURKEY", "lightning"),
    "TM" => __("TURKMENISTAN", "lightning"),
    "TC" => __("TURKS AND CAICOS ISLANDS", "lightning"),
    "TV" => __("TUVALU", "lightning"),
    "UG" => __("UGANDA", "lightning"),
    "UA" => __("UKRAINE", "lightning"),
    "AE" => __("UNITED ARAB EMIRATES", "lightning"),
    "GB" => __("UNITED KINGDOM", "lightning"),
    "US" => __("UNITED STATES", "lightning"),
    "UM" => __("UNITED STATES MINOR OUTLYING ISLANDS", "lightning"),
    "UY" => __("URUGUAY", "lightning"),
    "UZ" => __("UZBEKISTAN", "lightning"),
    "VU" => __("VANUATU", "lightning"),
    "VE" => __("VENEZUELA", "lightning"),
    "VN" => __("VIET NAM", "lightning"),
    "VG" => __("VIRGIN ISLANDS, BRITISH", "lightning"),
    "VI" => __("VIRGIN ISLANDS, U.S.", "lightning"),
    "WF" => __("WALLIS AND FUTUNA", "lightning"),
    "EH" => __("WESTERN SAHARA", "lightning"),
    "YE" => __("YEMEN", "lightning"),
    "ZM" => __("ZAMBIA", "lightning"),
    "ZW" => __("ZIMBABWE", "lightning")
];


$c_codes = [
    "af : afghanistan",
    "al : albania",
    "dz : algeria",
    "as : american samoa",
    "ad : andorra",
    "ao : angola",
    "aq : antarctica",
    "ag : antigua and barbuda",
    "ar : argentina",
    "am : armenia",
    "aw : aruba",
    "au : australia",
    "at : austria",
    "az : azerbaijan",
    "bs : bahamas",
    "bh : bahrain",
    "bd : bangladesh",
    "bb : barbados",
    "by : belarus",
    "be : belgium",
    "bz : belize",
    "bj : benin",
    "bm : bermuda",
    "bt : bhutan",
    "bo : bolivia",
    "ba : bosnia and herzegovina",
    "bw : botswana",
    "bv : bouvet island",
    "br : brazil",
    "io : british indian ocean territory",
    "bn : brunei darussalam",
    "bg : bulgaria",
    "bf : burkina faso",
    "bi : burundi",
    "kh : cambodia",
    "cm : cameroon",
    "ca : canada",
    "cv : cape verde",
    "ky : cayman islands",
    "cf : central african republic",
    "td : chad",
    "cl : chile",
    "cn : china",
    "cx : christmas island",
    "cc : cocos (keeling) islands",
    "co : colombia",
    "km : comoros",
    "cg : congo",
    "cd : congo, the democratic republic of the",
    "ck : cook islands",
    "cr : costa rica",
    "ci : côte d'ivoire",
    "hr : croatia",
    "cu : cuba",
    "cy : cyprus",
    "cz : czech republic",
    "dk : denmark",
    "dj : djibouti",
    "dm : dominica",
    "do : dominican republic",
    "ec : ecuador",
    "eg : egypt",
    "sv : el salvador",
    "gq : equatorial guinea",
    "er : eritrea",
    "ee : estonia",
    "et : ethiopia",
    "fk : falkland islands (malvinas)",
    "fo : faroe islands",
    "fj : fiji",
    "fi : finland",
    "fr : france",
    "gf : french guiana",
    "pf : french polynesia",
    "tf : french southern territories",
    "ga : gabon",
    "gm : gambia",
    "ge : georgia",
    "de : germany",
    "gh : ghana",
    "gi : gibraltar",
    "gr : greece",
    "gl : greenland",
    "gd : grenada",
    "gp : guadeloupe",
    "gu : guam",
    "gt : guatemala",
    "gn : guinea",
    "gw : guinea-bissau",
    "gy : guyana",
    "ht : haiti",
    "hm : heard island and mcdonald islands",
    "hn : honduras",
    "hk : hong kong",
    "hu : hungary",
    "is : iceland",
    "in : india",
    "id : indonesia",
    "ir : iran, islamic republic of",
    "iq : iraq",
    "ie : ireland",
    "il : israel",
    "it : italy",
    "jm : jamaica",
    "jp : japan",
    "jo : jordan",
    "kz : kazakhstan",
    "ke : kenya",
    "ki : kiribati",
    "kp : korea, democratic people's republic of",
    "kr : korea, republic of",
    "kw : kuwait",
    "kg : kyrgyzstan",
    "la : lao people's democratic republic (laos)",
    "lv : latvia",
    "lb : lebanon",
    "ls : lesotho",
    "lr : liberia",
    "ly : libya, state of",
    "li : liechtenstein",
    "lt : lithuania",
    "lu : luxembourg",
    "mo : macao",
    "mk : macedonia, the former yugoslav republic of",
    "mg : madagascar",
    "mw : malawi",
    "my : malaysia",
    "mv : maldives",
    "ml : mali",
    "mt : malta",
    "mh : marshall islands",
    "mq : martinique",
    "mr : mauritania",
    "mu : mauritius",
    "yt : mayotte",
    "mx : mexico",
    "fm : micronesia, federated states of",
    "md : moldova, republic of",
    "mc : monaco",
    "mn : mongolia",
    "me : montenegro",
    "ms : montserrat",
    "ma : morocco",
    "mz : mozambique",
    "mm : myanmar",
    "na : namibia",
    "nr : nauru",
    "np : nepal, federal democratic republic of",
    "nl : netherlands",
    "an : netherlands antilles",
    "nc : new caledonia",
    "nz : new zealand",
    "ni : nicaragua",
    "ne : niger",
    "ng : nigeria",
    "nu : niue",
    "nf : norfolk island",
    "mp : northern mariana islands",
    "no : norway",
    "om : oman",
    "pk : pakistan",
    "pw : palau",
    "ps : palestine, state of",
    "pa : panama",
    "pg : papua new guinea",
    "py : paraguay",
    "pe : peru",
    "ph : philippines",
    "pn : pitcairn",
    "pl : poland",
    "pt : portugal",
    "pr : puerto rico",
    "qa : qatar",
    "re : réunion",
    "ro : romania",
    "ru : russian federation",
    "rw : rwanda",
    "sh : saint helena",
    "kn : saint kitts and nevis",
    "lc : saint lucia",
    "pm : saint pierre and miquelon",
    "vc : saint vincent and the grenadines",
    "ws : samoa",
    "sm : san marino",
    "st : sao tome and principe",
    "sa : saudi arabia",
    "sn : senegal",
    "rs : serbia",
    "sc : seychelles",
    "sl : sierra leone",
    "sg : singapore",
    "sk : slovakia",
    "si : slovenia",
    "sb : solomon islands",
    "so : somalia",
    "za : south africa",
    "gs : south georgia and the south sandwich islands",
    "ss : south sudan",
    "es : spain",
    "lk : sri lanka",
    "sd : sudan",
    "sr : suriname",
    "sj : svalbard and jan mayen",
    "sz : swaziland",
    "se : sweden",
    "ch : switzerland",
    "sy : syrian arab republic",
    "tw : taiwan",
    "tj : tajikistan",
    "tz : tanzania, united republic of",
    "th : thailand",
    "tl : timor-leste",
    "tg : togo",
    "tk : tokelau",
    "to : tonga",
    "tt : trinidad and tobago",
    "tn : tunisia",
    "tr : turkey",
    "tm : turkmenistan",
    "tc : turks and caicos islands",
    "tv : tuvalu",
    "ug : uganda",
    "ua : ukraine",
    "ae : united arab emirates",
    "gb : united kingdom",
    "us : united states",
    "um : united states minor outlying islands",
    "uy : uruguay",
    "uz : uzbekistan",
    "vu : vanuatu",
    "ve : venezuela",
    "vn : viet nam",
    "vg : virgin islands, british",
    "vi : virgin islands, u.s.",
    "wf : wallis and futuna",
    "eh : western sahara",
    "ye : yemen",
    "zm : zambia",
    "zw : zimbabwe",
];