<?php
include __DIR__ . '/acf-arrays/material-icons.php';

acf_add_local_field_group([
    'key' => 'group_theme_footer',
    'title' => 'Sidfoten',
    'fields' => [
        [
            'key' => 'field_lb_theme_footer_info_tab',
            'label' => 'Info',
            'type' => 'tab',
            'placement' => 'top',
        ],
        [
            'key' => 'field_lb_theme_footer_logo',
            'label' => 'Logga',
            'name' => 'footer_logo',
            'type' => 'image',
            'return_format' => 'id',
            'preview_size' => 'medium',
            'library' => 'all',
            'wrapper' => [
                'width' => '50',
            ]
        ],
        [
            'key' => 'field_lb_theme_footer_logo_dark',
            'label' => 'Logga i dark mode',
            'name' => 'footer_logo_dark',
            'type' => 'image',
            'return_format' => 'id',
            'preview_size' => 'medium',
            'library' => 'all',
            'wrapper' => [
                'width' => '50',
            ]
        ],
        [
            'key' => 'field_lb_theme_footer_footer_text',
            'label' => 'Text',
            'name' => 'footer_text',
            'type' => 'wysiwyg',
            'tabs' => 'visual',
            'toolbar' => 'basic',
            'media_upload' => 0,
            'delay' => 1,
        ],
        [
            'key' => 'field_lb_theme_footer_columns_tab',
            'label' => 'Kolumner',
            'type' => 'tab',
            'placement' => 'top',
        ],
        [
            'key' => 'field_lb_theme_footer_columns',
            'label' => 'Kolumner',
            'name' => 'footer_col_repeater',
            'type' => 'repeater',
            'instructions' => 'Max 2 kolumner',
            'max' => 2,
            'layout' => 'block',
            'button_label' => 'Kolumn +',
            'sub_fields' => [
                [
                    'key' => 'field_lb_theme_footer_columns_title',
                    'label' => 'Rubrik',
                    'name' => 'footer_col_title',
                    'type' => 'text',
                    'parent_repeater' => 'field_lb_theme_footer_columns',
                ],
                [
                    'key' => 'field_lb_theme_footer_col_links',
                    'label' => 'Länkar',
                    'name' => 'footer_col_links',
                    'type' => 'repeater',
                    'layout' => 'table',
                    'button_label' => 'Add Row',
                    'sub_fields' => [
                        [
                            'key' => 'field_lb_theme_footer_icon',
                            'label' => 'Ikon',
                            'name' => 'icon',
                            'type' => 'select',
                            'choices' => $icons,
                            'default_value' => false,
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 1,
                            'ajax' => 1,
                            'return_format' => 'label',
                            'parent_repeater' => 'field_lb_theme_footer_col_links',
                        ],
                        [
                            'key' => 'field_lb_theme_footer_col_link',
                            'label' => 'Länk',
                            'name' => 'footer_col_link',
                            'type' => 'link',
                            'return_format' => 'array',
                            'parent_repeater' => 'field_lb_theme_footer_col_links',
                        ],
                    ],
                    'rows_per_page' => 20,
                    'parent_repeater' => 'field_lb_theme_footer_columns',
                ],
            ],
            'rows_per_page' => 20,
        ],
        [
            'key' => 'field_lb_theme_footer_social_media_title',
            'label' => 'Rubrik för sociala medier',
            'name' => 'footer_title_social_media',
            'type' => 'text',
        ],
        [
            'key' => 'field_lb_theme_footer_social_media_tab',
            'label' => 'Sociala medier',
            'type' => 'tab',
            'placement' => 'top',
        ],
        [
            'key' => 'field_lb_theme_footer_social_media_repeater',
            'label' => 'Sociala medier',
            'name' => 'footer_col_social_media',
            'type' => 'repeater',
            'layout' => 'table',
            'button_label' => 'Add Row',
            'sub_fields' => [
                [
                    'key' => 'field_lb_theme_footer_social_media_icon',
                    'label' => 'Ikon',
                    'name' => 'footer_col_icon',
                    'type' => 'image',
                    'return_format' => 'id',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'parent_repeater' => 'field_lb_theme_footer_social_media_repeater',
                ],
                [
                    'key' => 'field_lb_theme_footer_col_link',
                    'label' => 'Länk',
                    'name' => 'footer_col_link',
                    'type' => 'link',
                    'return_format' => 'array',
                    'parent_repeater' => 'field_lb_theme_footer_social_media_repeater',
                ],
            ],
            'rows_per_page' => 20,
        ],
        [
            'key' => 'field_lb_theme_footer_social_media_text',
            'label' => 'Text',
            'name' => 'footer_col_social_media_text',
            'type' => 'wysiwyg',
            'tabs' => 'visual',
            'toolbar' => 'basic',
            'media_upload' => 0,
            'delay' => 1,
        ],
    ],
    'location' => [
        [
            [
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'theme-footer',
            ],
        ],
    ],
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'active' => true,
    'show_in_rest' => 0,
]);
