<?php
return [
    'key' => 'layout_columns',
    'name' => 'columns',
    'label' => 'Kolumner',
    'display' => 'block',
    'sub_fields' => [
        [
            'key' => 'field_lb_column_comp_head_tab',
            'label' => 'Komponenthuvud',
            'type' => 'tab',
            'placement' => 'top',
        ],
        [
            'key' => 'field_lb_column_header',
            'label' => 'Header',
            'name' => 'columns',
            'type' => 'clone',
            'clone' => [
                0 => 'group_clone_component_header',
            ],
            'display' => 'seamless',
            'prefix_name' => 1,
        ],
        [
            'key' => 'field_lb_column_content_tab',
            'label' => 'Innehåll',
            'type' => 'tab',
            'placement' => 'top',
        ],
        [
            'key' => 'field_lb_column_columns_cols',
            'label' => 'Kolumner',
            'name' => 'columns_cols',
            'type' => 'repeater',
            'layout' => 'block',
            'collapsed' => 'field_lb_column_col_title',
            'button_label' => 'Kolumn +',
            'rows_per_page' => 20,
            'sub_fields' => [
                [
                    'key' => 'field_lb_column_cols_content_tab',
                    'label' => 'Innehåll',
                    'type' => 'tab',
                    'placement' => 'top',
                    'parent_repeater' => 'field_lb_column_columns_cols',

                ],
                [
                    'key' => 'field_lb_column_col_media_type',
                    'label' => 'Mediatyp',
                    'name' => 'media_type',
                    'type' => 'button_group',
                    'wrapper' => [
                        'width' => '50',
                    ],
                    'choices' => [
                        'img' => 'Bild',
                        'video' => 'Video',
                        'icon' => 'Ikon',
                    ],
                    'allow_null' => 0,
                    'layout' => 'horizontal',
                    'return_format' => 'value',
                    'parent_repeater' => 'field_lb_column_columns_cols',
                ],
                [
                    'key' => 'field_lb_column_col_link',
                    'label' => 'Knapp/Länk',
                    'name' => 'link',
                    'type' => 'link',
                    'instructions' => 'Utelämna rubriken i länken för att länka hela kolumnen. <br>
Annars visas en knapp/länk längst ner.',
                    'wrapper' => ['width' => '50'],
                    'return_format' => 'array',
                    'parent_repeater' => 'field_lb_column_columns_cols',
                ],
                [
                    'key' => 'field_lb_column_col_img',
                    'label' => 'Bild',
                    'name' => 'img',
                    'type' => 'image',
                    'wrapper' => ['width' => '50'],
                    'return_format' => 'id',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'parent_repeater' => 'field_lb_column_columns_cols',
                    'conditional_logic' => [
                        [
                            [
                                'field' => 'field_lb_column_col_media_type',
                                'operator' => '==',
                                'value' => 'img',
                            ],
                        ],
                    ],
                ],
                [
                    'key' => 'field_lb_column_col_icon',
                    'label' => 'Ikon',
                    'name' => 'icon',
                    'type' => 'select',
                    'conditional_logic' => [
                        [
                            [
                                'field' => 'field_lb_column_col_media_type',
                                'operator' => '==',
                                'value' => 'icon',
                            ],
                        ],
                    ],
                    'wrapper' => [
                        'width' => '50',
                    ],
                    'choices' => $icons,
                    'default_value' => false,
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 1,
                    'ajax' => 1,
                    'return_format' => 'label',
                    'parent_repeater' => 'field_lb_column_columns_cols',
                ],
                [
                    'key' => 'field_lb_column_col_video',
                    'label' => 'Video',
                    'name' => 'video',
                    'type' => 'file',
                    'mime_types' => 'mp4',
                    'return_format' => 'id',
                    'library' => 'all',
                    'parent_repeater' => 'field_lb_column_columns_cols',
                    'wrapper' => ['width' => '50'],
                    'conditional_logic' => [
                        [
                            [
                                'field' => 'field_lb_column_col_media_type',
                                'operator' => '==',
                                'value' => 'video',
                            ],
                        ],
                    ],
                ],
                [
                    'key' => 'field_lb_column_col_title',
                    'label' => 'Rubrik',
                    'name' => 'title',
                    'type' => 'text',
                    'parent_repeater' => 'field_lb_column_columns_cols',
                ],
                [
                    'key' => 'field_lb_column_col_text',
                    'label' => 'Text',
                    'name' => 'text',
                    'type' => 'wysiwyg',
                    'tabs' => 'visual',
                    'toolbar' => 'basic',
                    'media_upload' => 0,
                    'delay' => 1,
                    'parent_repeater' => 'field_lb_column_columns_cols',
                ],
                [
                    'key' => 'field_lb_column_col_color_tab',
                    'label' => 'Färger',
                    'type' => 'tab',
                    'placement' => 'top',
                    'parent_repeater' => 'field_lb_column_columns_cols',
                ],
                [
                    'key' => 'field_lb_column_col_inherit',
                    'label' => 'Ärv?',
                    'name' => 'inherit',
                    'type' => 'true_false',
                    'instructions' => 'Välj om du vill ärva färgen från huvudkomponenten eller sätta en egen för kolumnen.',
                    'message' => '',
                    'default_value' => 1,
                    'ui' => 1,
                    'ui_on_text' => 'Ja',
                    'ui_off_text' => 'Nej',
                    'parent_repeater' => 'field_lb_column_columns_cols',
                ],
                [
                    'key' => 'field_lb_column_col_color',
                    'label' => 'Färger',
                    'name' => 'col_color',
                    'type' => 'clone',
                    'clone' => [
                        0 => 'field_clone_bg_colors',
                        1 => 'field_clone_text_colors',
                    ],
                    'display' => 'seamless',
                    'layout' => 'block',
                    'prefix_name' => 1,
                    'parent_repeater' => 'field_lb_column_columns_cols',
                ],
            ],
        ],
        [
            'key' => 'field_lb_column_settings_tab',
            'label' => 'Inställningar',
            'type' => 'tab',
            'placement' => 'top',
        ],
        [
            'key' => 'field_lb_column_col_card_view',
            'label' => __('Använd kortvy', 'lightning'),
            'name' => 'card_view',
            'type' => 'true_false',
            'message' => 'Visa innehållet som kort',
            'default_value' => 1,
            'ui' => 1,
            'ui_on_text' => 'Ja',
            'ui_off_text' => 'Nej',
            'wrapper' => ['width' => '50'],
        ],
        [
            'key' => 'field_lb_column_col_qty',
            'label' => __('Antal kolumner', 'lightning'),
            'name' => 'col_qty',
            'type' => 'range',
            'instructions' => __('I hur många kolumner vill du visa inläggen? Min 2, max 4.', 'lightning'),
            'min' => '2',
            'max' => '4',
            'step' => '1',
            'default_value' => '4',
            'wrapper' => ['width' => '50']
        ],
        [
            'key' => 'field_lb_column_columns',
            'label' => 'Färger',
            'name' => 'columns',
            'type' => 'clone',
            'clone' => [
                0 => 'group_clone_component_settings',
            ],
            'display' => 'seamless',
            'layout' => 'block',
            'prefix_name' => 1,
        ],
        [
            'key' => 'field_lb_column_component_id',
            'label' => 'Komponentens id (frivillig)',
            'name' => 'component_id',
            'type' => 'text',
            'instructions' => $component_id_instructions,
            'placeholder' => 'my-id',
            'prepend' => '#',
        ]
    ],
];
